### ISSUE TITLE
Nextcloud App Store Availability

### ISSUE THREAD

**Issue by HammyHavoc** [mrzapp/nextcloud-crop-planner#1]
Would be great if this was available via the Nextcloud App Store! :- )

**Comment by mrzapp** [comment]
@HammyHavoc I'm glad you like it, and I can totally see the need for app like this in the NextCloud community.

This was however just a quick experiment, and I'd prefer not to take it to the next level, since I won't even use it myself. That was the case with the [cookbook](https://github.com/nextcloud/cookbook/) app, which suddenly exploded in popularity, and it took me forever to get it off my hands :sweat_smile: 

You're more than welcome to fork the project, though.
